description = 'stagediver.fx - Lookup'
dependencies {
    compile 'javax.enterprise:cdi-api'
    compile 'org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec'
    compile 'com.google.guava:guava'
    compile 'org.apache.commons:commons-lang3'
}

task packageTests(type: Jar) {
    from sourceSets.test.output
    classifier = 'tests'
}
artifacts.archives packageTests
