<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.softwareecg.wfx</groupId>
        <artifactId>wfx</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <description>wfx - Window Manager Core</description>

    <artifactId>windowmanager-core</artifactId>


    <dependencies>

        <!-- project dependencies -->

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>windowmanager-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>platform-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>platform-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>lookup</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- misc libs -->

        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-junit</artifactId>
            <version>4.0.13-alpha</version>
            <scope>test</scope>
        </dependency>


        <!-- unit test dependencies -->

        <dependency>
            <groupId>org.loadui</groupId>
            <artifactId>testFx</artifactId>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>windowmanager-api</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>lookup-serviceloader</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --add-opens io.softwareecg.wfx.windowmanager.api/io.softwareecg.wfx.windowmtg.api=io.softwareecg.wfx.windowmanager.core
                        --add-opens io.softwareecg.wfx.windowmanager.core/io.softwareecg.wfx.windowmtg.impl=ALL-UNNAMED
                        --add-opens io.softwareecg.wfx.windowmanager.core/io.softwareecg.wfx.windowmtg.impl=org.apache.commons.lang3
                        --add-opens io.softwareecg.wfx.windowmanager.core/io.softwareecg.wfx.windowmtg.windows=ALL-UNNAMED
                        --add-opens javafx.graphics/javafx.stage=org.apache.commons.lang3
                        --add-opens javafx.graphics/javafx.scene=org.apache.commons.lang3
                        --add-opens javafx.graphics/javafx.scene.layout=org.apache.commons.lang3
                        --add-opens javafx.base/javafx.beans.property=org.apache.commons.lang3
                        --add-opens javafx.controls/javafx.scene.control=org.apache.commons.lang3
                        --add-reads io.softwareecg.wfx.windowmanager.core=ALL-UNNAMED
                        --add-reads io.softwareecg.wfx.windowmanager.core=org.mockito
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
