plugins {
    id 'java'          // oder: id 'java-library' / id 'application'
}
description = 'stagediver.fx - Example-GUI'


repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
    implementation 'de.qaware.stagediver.fx:windowmanager-api:1.4.0-SNAPSHOT'
    implementation 'de.qaware.stagediver.fx:windowmanager-core:1.4.0-SNAPSHOT'
    implementation 'de.qaware.stagediver.fx:lookup-cdi:1.4.0-SNAPSHOT'
    implementation 'de.qaware.stagediver.fx:platform-api:1.4.0-SNAPSHOT'
    implementation 'de.qaware.stagediver.fx:platform-core:1.4.0-SNAPSHOT'
    implementation 'de.qaware.stagediver.fx:platform-runner:1.4.0-SNAPSHOT'
    implementation 'de.qaware.stagediver.fx.extensions:ui-utils:1.4.0-SNAPSHOT'
    // implementation 'de.qaware.stagediver.fx.extensions:logger-console:1.4.0-SNAPSHOT'
    // implementation 'de.qaware.stagediver.fx.extensions:logger-console-logback:1.4.0-SNAPSHOT'
    implementation 'ch.qos.logback:logback-classic:1.5.20'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

test {
    useJUnitPlatform()
}
