<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>${groupId}</groupId>
    <artifactId>${artifactId}</artifactId>
    <packaging>pom</packaging>
    <version>${version}</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.version>7</project.build.version>
        <version.stagediver>1.0-SNAPSHOT</version.stagediver>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${groupId}</groupId>
                <artifactId>${artifactId}-editor</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${groupId}</groupId>
                <artifactId>${artifactId}-branding</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>lookup</artifactId>
                <version>${version.stagediver}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-core</artifactId>
                <version>${version.stagediver}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-api</artifactId>
                <version>${version.stagediver}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-runner</artifactId>
                <version>${version.stagediver}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-api</artifactId>
                <version>${version.stagediver}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-core</artifactId>
                <version>${version.stagediver}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-non-osgi</artifactId>
                <version>${version.stagediver}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.core</artifactId>
                <version>4.3.1</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.compendium</artifactId>
                <version>4.3.1</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>1.7.5</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>2.5.1</version>
                    <configuration>
                        <source>${project.build.version}</source>
                        <target>${project.build.version}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <version>2.3.7</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-scr-plugin</artifactId>
                    <version>1.13.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-scr-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-scr-scrdescriptor</id>
                        <goals>
                            <goal>scr</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${project.build.version}</source>
                    <target>${project.build.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>qaware-nexus</id>
            <url>https://neu.qaware.de/nexus/content/repositories/QAWARE-STAGEDIVER-FX/</url>
            <releases>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>qaware-nexus-snapshots</id>
            <url>https://neu.qaware.de/nexus/content/repositories/QAWARE-STAGEDIVER-FX-SNAPSHOTS/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
            </snapshots>
        </repository>
    </repositories>
</project>
