# ______________________________________________________________________________
#          Project: stagediver.fx
# ______________________________________________________________________________
#
#       created by: christian.fritz
#    creation date: 24.07.14 17:41
#      description:
# ______________________________________________________________________________
#
#        Copyright: (c) QAware GmbH, all rights reserved
# ______________________________________________________________________________

version=${project.version}
