<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>stagediver.fx</artifactId>
        <groupId>de.qaware.stagediver.fx</groupId>
        <version>0.5</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.qaware.stagediver.fx.extensions</groupId>
    <artifactId>extensions</artifactId>
    <packaging>pom</packaging>
    <name>stagediver.fx - Extensions</name>
    <modules>
        <module>logger-console</module>
        <module>ui-utils</module>
        <module>logger-console-api</module>
        <module>logger-console-logback</module>
    </modules>

</project>