<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>itests</artifactId>
        <groupId>de.qaware.stagediver.fx</groupId>
        <version>0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>itests-windowmanager</artifactId>
    <packaging>jar</packaging>

    <name>stagediver.fx - Window Manager UI Integration Tests</name>


    <dependencies>
        <dependency>
            <groupId>de.qaware.stagediver.fx</groupId>
            <artifactId>lookup</artifactId>
        </dependency>
        <dependency>
            <groupId>de.qaware.stagediver.fx</groupId>
            <artifactId>windowmanager-api</artifactId>
        </dependency>
        <dependency>
            <groupId>de.qaware.stagediver.fx</groupId>
            <artifactId>windowmanager-core</artifactId>
        </dependency>

        <dependency>
            <groupId>de.qaware.stagediver.fx</groupId>
            <artifactId>windowmanager-core</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
        </dependency>
        
        <dependency>
            <groupId>org.loadui</groupId>
            <artifactId>testFx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
        </dependency>
    </dependencies>
</project>
