<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.qaware.stagediver.fx</groupId>
    <artifactId>stagediver.fx</artifactId>
    <packaging>pom</packaging>
    <version>0.1-SNAPSHOT</version>
    <name>stagediver.fx</name>
    <organization>
        <name>QAware GmbH</name>
        <url>http://www.qaware.de/</url>
    </organization>
    <modules>
        <module>platform-runner</module>
        <module>platform-api</module>
        <module>platform-core</module>
        <module>lookup</module>
        <module>windowmanager-api</module>
        <module>windowmanager-core</module>
        <module>example-gui</module>
        <module>platform-full</module>
        <module>platform-non-osgi</module>
        <module>stagediverfx-maven-plugin</module>
        <module>stagediverfx-archetype-quickstart</module>
    </modules>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.version>7</project.build.version>
        <guava.version>14.0.1</guava.version>
        <osgi.version>4.3.1</osgi.version>
        <felix.version>4.2.1</felix.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Platform-Core-->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-runner</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>lookup</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- Window Management -->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Example GUI -->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>example-gui</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- OSGi Container - Felix -->
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.framework</artifactId>
                <version>${felix.version}</version>
                <type>jar</type>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.scr</artifactId>
                <version>1.6.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.scr.annotations</artifactId>
                <version>1.9.6</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.core</artifactId>
                <version>${osgi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.compendium</artifactId>
                <version>${osgi.version}</version>
            </dependency>

            <!-- Logging -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>1.7.5</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-log4j12</artifactId>
                <version>1.7.5</version>
            </dependency>
            <dependency>
                <groupId>org.ops4j.pax.logging</groupId>
                <artifactId>pax-logging-api</artifactId>
                <version>1.7.0</version>
            </dependency>
            <dependency>
                <groupId>org.ops4j.pax.logging</groupId>
                <artifactId>pax-logging-service</artifactId>
                <version>1.7.0</version>
            </dependency>

            <!-- Google Guava -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>

            <!-- Google Guice -->
            <dependency>
                <groupId>com.google.inject</groupId>
                <artifactId>guice</artifactId>
                <version>3.0</version>
                <exclusions>
                    <exclusion>
                        <groupId>aopalliance</groupId>
                        <artifactId>aopalliance</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.inject</groupId>
                        <artifactId>javax.inject</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- Apache ServiceMix OSGi Bundles as replaces to aopalliance and javax.inject -->
            <dependency>
                <groupId>org.apache.servicemix.bundles</groupId>
                <artifactId>org.apache.servicemix.bundles.aopalliance</artifactId>
                <version>1.0_6</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicemix.bundles</groupId>
                <artifactId>org.apache.servicemix.bundles.javax-inject</artifactId>
                <version>1_2</version>
            </dependency>

            <!-- Testing -->
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.11</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-all</artifactId>
                <version>1.9.5</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.javafx</groupId>
                <artifactId>javafx</artifactId>
                <version>${version.jfx}</version>
                <systemPath>${path.jfx}</systemPath>
                <scope>system</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>2.5.1</version>
                    <configuration>
                        <source>${project.build.version}</source>
                        <target>${project.build.version}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <version>2.3.7</version>
                    <extensions>true</extensions>
                </plugin>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-scr-plugin</artifactId>
                    <version>1.14.0</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.ow2.asm</groupId>
                            <artifactId>asm-all</artifactId>
                            <version>${version.asm}</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>generate-scr-scrdescriptor</id>
                            <goals>
                                <goal>scr</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${project.build.version}</source>
                    <target>${project.build.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>qaware-nexus</id>
            <url>https://neu.qaware.de/nexus/content/repositories/QAWARE-STAGEDIVER-FX/</url>
        </repository>
        <snapshotRepository>
            <id>qaware-nexus</id>
            <url>https://neu.qaware.de/nexus/content/repositories/QAWARE-STAGEDIVER-FX-SNAPSHOTS/</url>
        </snapshotRepository>
    </distributionManagement>

    <profiles>
        <profile>
            <activation>
                <jdk>[1.8,2.0)</jdk>
            </activation>
            <id>jdk8</id>
            <properties>
                <version.asm>5.0_ALPHA</version.asm>
                <version.jfx>8.0</version.jfx>
                <path.jfx>${java.home}/lib/ext/jfxrt.jar</path.jfx>
            </properties>
        </profile>
        <profile>
            <id>jdk7</id>
            <activation>
                <jdk>[1.7,1.8)</jdk>
            </activation>
            <properties>
                <version.asm>4.0</version.asm>
                <version.jfx>2.2</version.jfx>
                <path.jfx>${java.home}/lib/jfxrt.jar</path.jfx>
            </properties>
        </profile>
    </profiles>
</project>