<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.qaware.stagediver.fx</groupId>
    <artifactId>stagediver.fx</artifactId>
    <version>0.5-SNAPSHOT</version>
    <name>stagediver.fx</name>
    <description>stagediver.fx is a rich-client-platform for JavaFX.</description>
    <packaging>pom</packaging>

    <organization>
        <name>QAware GmbH</name>
        <url>http://www.qaware.de/</url>
    </organization>
    <prerequisites>
        <maven>3.0.4</maven>
    </prerequisites>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git@github.com:qaware/stagediver.fx.git</connection>
        <developerConnection>scm:git:git@github.com:qaware/stagediver.fx.git</developerConnection>
        <url>https://github.com/qaware/stagediver.fx</url>
        <tag>HEAD</tag>
    </scm>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/qaware/stagediver.fx/issues</url>
    </issueManagement>

    <developers>
        <developer>
            <id>chr-fritz</id>
            <name>Christian Fritz</name>
            <email>christian dot fritz at qaware dot de</email>
            <timezone>Europe/Berlin</timezone>
            <organization>QAware GmbH</organization>
            <organizationUrl>http://www.qaware.de</organizationUrl>
        </developer>
    </developers>

    <modules>
        <module>platform-runner</module>
        <module>platform-api</module>
        <module>platform-core</module>
        <module>lookup</module>
        <module>lookup-cdi</module>
        <module>windowmanager-api</module>
        <module>windowmanager-core</module>
        <module>stagediverfx-maven-plugin</module>
        <module>stagediverfx-archetype-quickstart</module>
        <module>example-gui</module>
        <module>platform-full</module>
        <module>extensions</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.version>8</project.build.version>
        <guava.version>19.0</guava.version>
        <version.jfx>8.0</version.jfx>
        <sonar.jacoco.itReportPath>${project.basedir}/../target/jacoco-it.exec</sonar.jacoco.itReportPath>
        <weld.version>2.3.2.Final</weld.version>
        <logback.version>1.1.3</logback.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Platform-Core-->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-runner</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-full</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>lookup</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>lookup</artifactId>
                <version>${project.version}</version>
                <type>test-jar</type>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>lookup-cdi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- Window Management -->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>stagediverfx-archetype-quickstart</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- stagediver.fx Extensions -->
            <dependency>
                <groupId>de.qaware.stagediver.fx.extensions</groupId>
                <artifactId>logger-console-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx.extensions</groupId>
                <artifactId>logger-console</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx.extensions</groupId>
                <artifactId>ui-utils</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- stagediver.fx logger console adapter -->
            <dependency>
                <groupId>de.qaware.stagediver.fx.extensions</groupId>
                <artifactId>logger-console-logback</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Example GUI -->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>example-gui</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Apache Commons -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.4</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>4.1</version>
            </dependency>

            <!--CDI & WELD-->
            <dependency>
                <groupId>javax.enterprise</groupId>
                <artifactId>cdi-api</artifactId>
                <version>1.2</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>javax.inject</groupId>
                <artifactId>javax.inject</artifactId>
                <version>1</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.jboss.weld.se</groupId>
                <artifactId>weld-se</artifactId>
                <version>${weld.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jboss.weld</groupId>
                <artifactId>weld-core</artifactId>
                <version>${weld.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jboss.spec.javax.annotation</groupId>
                <artifactId>jboss-annotations-api_1.2_spec</artifactId>
                <version>1.0.0.Final</version>
            </dependency>

            <!-- Logging -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>1.7.13</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-core</artifactId>
                <version>${logback.version}</version>
            </dependency>

            <!-- Google Guava -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>

            <!-- Testing -->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-api</artifactId>
                <version>${project.version}</version>
                <scope>test</scope>
                <type>test-jar</type>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.12</version>
                <scope>test</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.hamcrest</groupId>
                        <artifactId>hamcrest-core</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-all</artifactId>
                <version>1.3</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-all</artifactId>
                <version>1.10.19</version>
                <scope>test</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.hamcrest</groupId>
                        <artifactId>hamcrest-core</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.loadui</groupId>
                <artifactId>testFx</artifactId>
                <!-- stay at version 3.1.1. due to the ThreadDeath issue in 3.1.2 -->
                <version>3.1.1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>nl.jqno.equalsverifier</groupId>
                <artifactId>equalsverifier</artifactId>
                <version>1.7.5</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.maven.shared</groupId>
                <artifactId>maven-verifier</artifactId>
                <version>1.6</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-source-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <phase>deploy</phase>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>deploy</id>
                            <phase>deploy</phase>
                            <goals>
                                <goal>deploy</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.19</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>2.19</version>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.7.5.201505241946</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.3</version>
                    <configuration>
                        <source>${project.build.version}</source>
                        <target>${project.build.version}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>2.10</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>2.6</version>
                    <configuration>
                        <archive>
                            <manifest>
                                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                                <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                            </manifest>
                        </archive>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>license-maven-plugin</artifactId>
                    <version>1.8</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.1</version>
                <configuration>
                    <pushChanges>false</pushChanges>
                    <localCheckout>true</localCheckout>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <preparationGoals>clean install</preparationGoals>
                    <goals>deploy</goals>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${project.build.version}</source>
                    <target>${project.build.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>Analyze Dependencies</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>analyze-only</goal>
                        </goals>
                        <configuration>
                            <failOnWarning>true</failOnWarning>
                            <ignoreNonCompile>true</ignoreNonCompile>
                            <outputXML>true</outputXML>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.10.3</version>
                <configuration>
                    <additionalparam>-Xdoclint:none</additionalparam>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
            <plugin>
                <!-- explicitly define maven-deploy-plugin after other to force exec order -->
                <artifactId>maven-deploy-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <configuration>
                    <licenseName>apache_v2</licenseName>
                    <projectName>${project.description}</projectName>
                    <inceptionYear>2013</inceptionYear>
                    <organizationName>QAware GmbH</organizationName>
                    <!-- only add license to *.java files -->
                    <includes>
                        <include>**/*.java</include>
                    </includes>
                    <!-- insert the license at the top of the file-->
                    <addJavaLicenseAfterPackage>false</addJavaLicenseAfterPackage>
                </configuration>
                <executions>
                    <execution>
                        <id>update-license-headers</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>update-file-header</goal>
                        </goals>
                        <configuration>
                            <!-- only auto-update generated code files-->
                            <roots>
                                <root>target/generated-sources</root>
                                <root>target/processed-sources</root>
                            </roots>
                        </configuration>
                    </execution>
                    <execution>
                        <id>check-license-headers</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>check-file-header</goal>
                        </goals>
                        <configuration>
                            <!-- fail build if license headers are not up-to-date-->
                            <failOnMissingHeader>true</failOnMissingHeader>
                            <failOnNotUptodateHeader>true</failOnNotUptodateHeader>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>qaware-nexus</id>
            <url>https://www.qaware.de/nexus/content/repositories/qaware-internal/</url>
        </repository>
        <snapshotRepository>
            <id>qaware-nexus</id>
            <url>https://www.qaware.de/nexus/content/repositories/qaware-internal-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <profiles>
        <profile>
            <id>itests</id>
            <modules>
                <module>itests</module>
            </modules>
        </profile>
    </profiles>
</project>
