<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.qaware.stagediver.fx</groupId>
    <artifactId>stagediver.fx</artifactId>
    <version>0.1-SNAPSHOT</version>
    <name>stagediver.fx</name>
    <description>stagediver.fx is a rich-client-platform for JavaFX.</description>
    <packaging>pom</packaging>

    <organization>
        <name>QAware GmbH</name>
        <url>http://www.qaware.de/</url>
    </organization>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git@github.com:qaware/stagediver.fx.git</connection>
        <developerConnection>scm:git:git@github.com:qaware/stagediver.fx.git</developerConnection>
        <url>https://github.com/qaware/stagediver.fx</url>
    </scm>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/qaware/stagediver.fx/issues</url>
    </issueManagement>

    <developers>
        <developer>
            <id>chr-fritz</id>
            <name>Christian Fritz</name>
            <email>christian dot fritz at qaware dot de</email>
            <timezone>Europe/Berlin</timezone>
            <organization>QAware GmbH</organization>
            <organizationUrl>http://www.qaware.de</organizationUrl>
        </developer>
    </developers>

    <modules>
        <module>platform-runner</module>
        <module>platform-api</module>
        <module>platform-core</module>
        <module>lookup</module>
        <module>lookup-cdi</module>
        <module>lookup-guice</module>
        <module>windowmanager-api</module>
        <module>windowmanager-core</module>
        <module>stagediverfx-maven-plugin</module>
        <module>stagediverfx-archetype-quickstart</module>
        <module>example-gui</module>
        <module>platform-full</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.version>8</project.build.version>
        <guava.version>18.0</guava.version>
        <version.asm>5.0.3</version.asm>
        <version.jfx>8.0</version.jfx>
        <sonar.jacoco.itReportPath>${project.basedir}/../target/jacoco-it.exec</sonar.jacoco.itReportPath>
        <guice.version>3.0</guice.version>
        <version.asm>5.0</version.asm>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Platform-Core-->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-runner</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>platform-full</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>lookup</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>lookup</artifactId>
                <version>${project.version}</version>
                <type>test-jar</type>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>lookup-cdi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>lookup-guice</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- Window Management -->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>stagediverfx-archetype-quickstart</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Example GUI -->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>example-gui</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Apache Commons -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.3.2</version>
            </dependency>

            <!--CDI & WELD-->
            <dependency>
                <groupId>javax.enterprise</groupId>
                <artifactId>cdi-api</artifactId>
                <version>1.2</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>javax.inject</groupId>
                <artifactId>javax.inject</artifactId>
                <version>1</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.jboss.weld.se</groupId>
                <artifactId>weld-se</artifactId>
                <version>2.2.9.Final</version>
            </dependency>
            <dependency>
                <groupId>org.jboss.weld</groupId>
                <artifactId>weld-core</artifactId>
                <version>2.2.9.Final</version>
            </dependency>
            <dependency>
                <groupId>org.jboss.spec.javax.annotation</groupId>
                <artifactId>jboss-annotations-api_1.2_spec</artifactId>
                <version>1.0.0.Alpha1</version>
            </dependency>

            <!-- Logging -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>1.7.7</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>1.1.2</version>
            </dependency>

            <!-- Google Guava -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>

            <!-- Google Guice -->
            <dependency>
                <groupId>com.google.inject</groupId>
                <artifactId>guice</artifactId>
                <version>${guice.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.inject.extensions</groupId>
                <artifactId>guice-multibindings</artifactId>
                <version>${guice.version}</version>
            </dependency>

            <!-- Testing -->
            <dependency>
                <groupId>de.qaware.stagediver.fx</groupId>
                <artifactId>windowmanager-api</artifactId>
                <version>${project.version}</version>
                <scope>test</scope>
                <type>test-jar</type>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.12</version>
                <scope>test</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.hamcrest</groupId>
                        <artifactId>hamcrest-core</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-all</artifactId>
                <version>1.3</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-all</artifactId>
                <version>1.10.8</version>
                <scope>test</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.hamcrest</groupId>
                        <artifactId>hamcrest-core</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.loadui</groupId>
                <artifactId>testFx</artifactId>
                <version>3.1.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.maven.shared</groupId>
                <artifactId>maven-verifier</artifactId>
                <version>1.5</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.16</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>2.16</version>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.7.1.201405082137</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>2.5.1</version>
                    <configuration>
                        <source>${project.build.version}</source>
                        <target>${project.build.version}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>2.6</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${project.build.version}</source>
                    <target>${project.build.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <executions>
                    <execution>
                        <id>Analyze Dependencies</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>analyze-only</goal>
                        </goals>
                        <configuration>
                            <failOnWarning>true</failOnWarning>
                            <ignoreNonCompile>true</ignoreNonCompile>
                            <outputXML>true</outputXML>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18</version>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>qaware-nexus</id>
            <url>https://www.qaware.de/nexus/content/repositories/QAWARE-STAGEDIVER-FX/</url>
        </repository>
        <snapshotRepository>
            <id>qaware-nexus</id>
            <url>https://www.qaware.de/nexus/content/repositories/QAWARE-STAGEDIVER-FX-SNAPSHOTS/</url>
        </snapshotRepository>
    </distributionManagement>

    <profiles>
        <profile>
            <id>itests</id>
            <modules>
                <module>itests</module>
            </modules>
        </profile>
    </profiles>
</project>
