rootProject.name = 'stagediver.fx'
include ':platform-runner'
include ':platform-api'
include ':platform-core'
include ':lookup'
include ':lookup-cdi'
include ':windowmanager-api'
include ':windowmanager-core'
//include ':stagediverfx-maven-plugin'
//include ':stagediverfx-archetype-quickstart'
include ':example-gui'
include ':platform-full'
include ':extensions:logger-console'
include ':extensions:ui-utils'
include ':extensions:logger-console-api'
include ':extensions:logger-console-logback'
include ':extensions'