description = 'stagediver.fx - Window Manager Core'

dependencies {
    compile project(':windowmanager-api')
    compile project(':platform-api')
    compile project(':platform-core')
    compile project(':lookup')

    compile 'javax.inject:javax.inject'
    compile 'org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec'

    compile 'org.jboss.weld.se:weld-se-core'
    compile 'org.apache.commons:commons-lang3'
    compile 'com.google.guava:guava'

    testCompile project(path: ':windowmanager-api', configuration: 'tests')
    testCompile project(path: ':lookup-cdi', configuration: 'tests')
    testCompile 'org.jboss.weld.se:weld-se-core'
    testCompile 'org.loadui:testFx'
}
sourceSets {
    main {
        // Workaround for tests with CDI. Ensures the META-INF/beans.xml within the same directory as the class files.
        output.resourcesDir = 'build/classes/main'
    }
    test {
        // Workaround for tests with CDI. Ensures the META-INF/beans.xml within the same directory as the class files.
        output.resourcesDir = 'build/classes/test'
    }
}
task jarTests(type: Jar, dependsOn: testClasses) {
    classifier = 'tests'
    from sourceSets.test.output
}
configurations {
    tests {
        extendsFrom testRuntime
    }
}
artifacts {
    tests jarTests
}