<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.qaware.stagediver.fx</groupId>
        <artifactId>stagediver-fx</artifactId>
        <version>1.1.1-SNAPSHOT</version>
    </parent>

    <description>stagediver.fx - Window Manager Core</description>

    <artifactId>windowmanager-core</artifactId>
    <version>1.1.1-SNAPSHOT</version>


    <dependencies>

        <!-- project dependencies -->

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>windowmanager-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>platform-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>platform-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>lookup</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- misc libs -->

        <dependency>
            <groupId>org.jboss.weld.se</groupId>
            <artifactId>weld-se-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-junit</artifactId>
            <version>4.0.13-alpha</version>
            <scope>test</scope>
        </dependency>


        <!-- unit test dependencies -->

        <dependency>
            <groupId>org.loadui</groupId>
            <artifactId>testFx</artifactId>
        </dependency>

    </dependencies>
</project>