<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>platform-core</artifactId>
    <description>wfx - Platform Core</description>

    <parent>
        <groupId>io.softwareecg.wfx</groupId>
        <artifactId>wfx</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <properties>
        <avaje.version>11.4</avaje.version>
    </properties>

    <dependencies>
        <!-- project dependencies -->

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>windowmanager-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>platform-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>lookup-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Avaje Inject runtime -->
        <dependency>
            <groupId>io.avaje</groupId>
            <artifactId>avaje-inject</artifactId>
            <version>${avaje.version}</version>
        </dependency>

        <!-- unit test dependencies -->

        <!-- https://mvnrepository.com/artifact/org.testfx/testfx-junit -->
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-junit</artifactId>
            <version>4.0.18</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.loadui</groupId>
            <artifactId>testFx</artifactId>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>windowmanager-api</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths combine.children="append">
                        <path>
                            <groupId>io.avaje</groupId>
                            <artifactId>avaje-inject-generator</artifactId>
                            <version>${avaje.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --add-opens io.softwareecg.wfx.platform.core/io.softwareecg.wfx.platform.core=ALL-UNNAMED
                        --add-opens io.softwareecg.wfx.platform.core/io.softwareecg.wfx.platform.core.eventbus=ALL-UNNAMED
                        --add-opens io.softwareecg.wfx.platform.core/io.softwareecg.wfx.platform.core.fxml=ALL-UNNAMED
                        --add-reads io.softwareecg.wfx.platform.core=ALL-UNNAMED
                        --add-reads io.softwareecg.wfx.platform.core=org.mockito
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
