<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.weigend.wfx</groupId>
        <artifactId>extensions</artifactId>
        <version>6.2.1-SNAPSHOT</version>
    </parent>

    <description>wfx - Extension - CDI Contexts</description>

    <artifactId>cdi-contexts</artifactId>
    <version>6.2.1-SNAPSHOT</version>

    <dependencies>

        <dependency>
            <groupId>de.weigend.wfx</groupId>
            <artifactId>lookup</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>de.weigend.wfx</groupId>
            <artifactId>windowmanager-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jboss.weld.se</groupId>
            <artifactId>weld-se-core</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>

        <!-- ******** test dependencies ************ -->

        <dependency>
            <groupId>de.weigend.wfx</groupId>
            <artifactId>lookup-cdi</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>de.weigend.wfx</groupId>
            <artifactId>windowmanager-api</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>de.weigend.wfx</groupId>
            <artifactId>windowmanager-core</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.jboss.arquillian.container</groupId>
            <artifactId>arquillian-weld-embedded</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jboss.shrinkwrap</groupId>
            <artifactId>shrinkwrap-api</artifactId>
            <version>1.2.6</version>
        </dependency>

        <dependency>
            <groupId>org.loadui</groupId>
            <artifactId>testFx</artifactId>
        </dependency>




    </dependencies>

</project>