#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
stagediver.auto.deploy.dir=bundles
org.osgi.framework.system.packages.extra=javafx.animation, javafx.application, javafx.beans, javafx.beans.binding,${symbol_escape}
  javafx.beans.property, javafx.beans.property.adapter, javafx.beans.value, javafx.collections, javafx.concurrent, ${symbol_escape}
  javafx.embed.swing, javafx.embed.swt, javafx.event, javafx.fxml, javafx.geometry, javafx.scene, javafx.scene.canvas,${symbol_escape}
  javafx.scene.chart, javafx.scene.control, javafx.scene.control.cell, javafx.scene.effect, javafx.scene.image, ${symbol_escape}
  javafx.scene.input, javafx.scene.layout, javafx.scene.media, javafx.scene.paint, javafx.scene.shape, ${symbol_escape}
  javafx.scene.text, javafx.scene.transform, javafx.scene.web, javafx.stage, javafx.util, javafx.util.converter,${symbol_escape}
  com.sun.javafx.application
org.osgi.framework.bundle.parent=app
org.osgi.framework.storage.clean=onFirstInit
org.osgi.framework.bootdelegation=javafx.*,com.sun.javafx.*,org.aopalliance.*,com.google.inject.*
org.osgi.framework.startlevel.beginning=5
felix.startlevel.bundle=5
felix.log.level=1
stagediver.auto.deploy.startlevel.bundle=de.qaware.stagediver.fx.platform-core@2 org.apache.felix.gogo.shell@1 ${symbol_escape}
  org.apache.felix.gogo.command@1 org.apache.felix.gogo.runtime@1 org.ops4j.pax.logging.pax-logging-service@1 ${symbol_escape}
  de.qaware.stagediver.fx.windowmanager-core@2 de.qaware.stagediver.fx.platform-api@1 ${symbol_escape}
  de.qaware.stagediver.fx.windowmanager-api@1