group = 'de.qaware.stagediver.fx.extensions'
description = 'stagediver.fx - Extension - Logger Console'
dependencies {
    compile project(':extensions:logger-console-api')
    compile project(':platform-api')
    compile project(':lookup')
    compile project(':windowmanager-api')
    compile project(':extensions:ui-utils')

    testCompile project(':windowmanager-api')
    testCompile 'org.loadui:testFx'
}
