<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>stagediver.fx</artifactId>
        <groupId>de.qaware.stagediver.fx</groupId>
        <version>0.6-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>itests</artifactId>
    <packaging>pom</packaging>
    <name>stagediver.fx - Integration Tests Parent</name>
    <modules>
        <module>itests-windowmanager</module>
        <module>itests-archetype-quickstart</module>
    </modules>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <forkMode>always</forkMode>
                        <includes>
                            <include>**/*Test.java</include>
                            <include>**/*TestSuite.java</include>
                            <include>**/*TestCase.java</include>
                            <include>**/*Spec.java</include>
                        </includes>
                        <excludes>
                            <exclude>**/*SlowTest.java</exclude>
                            <exclude>**/*FunctionalTest*.java</exclude>
                            <exclude>**/*UITest*.java</exclude>
                            <exclude>**/*IntegrationTest*.java</exclude>
                            <exclude>**/*IntegrationSpec.java</exclude>
                            <exclude>**/*SmokeTest.java</exclude>
                            <exclude>**/*SmokeSpec.java</exclude>
                            <exclude>**/*AcceptanceTest*.java</exclude>
                            <exclude>**/*RegressionTest.java</exclude>
                            <exclude>**/*ManualTest.java</exclude>
                            <include>**/*SeleniumTest.java</include>
                        </excludes>
                    </configuration>
                </plugin>
                <!--                <plugin>
                                    <groupId>org.jacoco</groupId>
                                    <artifactId>jacoco-maven-plugin</artifactId>
                                    <version>0.6.5.201403032054</version>
                                    <configuration>
                                        <destFile>${sonar.jacoco.itReportPath}</destFile>
                                        &lt;!&ndash;<dataFile>${sonar.jacoco.itReportPath}</dataFile>&ndash;&gt;
                                        <propertyName>jacoco.agent.argLine</propertyName>
                                        <append>true</append>
                                    </configuration>
                                    <executions>
                                        <execution>
                                            <id>pre-integration-test</id>
                                            <phase>pre-integration-test</phase>
                                            <goals>
                                                <goal>prepare-agent</goal>
                                            </goals>
                                        </execution>
                                        <execution>
                                            <id>post-integration-test</id>
                                            <phase>post-integration-test</phase>
                                            <goals>
                                                <goal>report</goal>
                                            </goals>
                                        </execution>
                                    </executions>
                                </plugin>-->
                <plugin>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <executions>
                        <execution>
                            <goals>
                                <goal>integration-test</goal>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <!--<argLine>${jacoco.agent.argLine}</argLine>-->
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <includes>
                            <include>**/*SlowTest.java</include>
                            <include>**/*FunctionalTest*.java</include>
                            <include>**/*UITest*.java</include>
                            <include>**/*IntegrationTest*.java</include>
                            <include>**/*IntegrationSpec.java</include>
                            <include>**/*SmokeTest.java</include>
                            <include>**/*SmokeSpec.java</include>
                            <include>**/*AcceptanceTest*.java</include>
                            <include>**/*RegressionTest.java</include>
                            <include>**/*SeleniumTest.java</include>
                        </includes>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
            <!--            <plugin>
                            <groupId>org.jacoco</groupId>
                            <artifactId>jacoco-maven-plugin</artifactId>
                        </plugin>-->
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>loaduiRepository</id>
            <url>http://www.soapui.org/repository/maven2/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>loaduiRepository</id>
            <url>http://www.soapui.org/repository/maven2/</url>
        </pluginRepository>
    </pluginRepositories>
</project>